### ISSUE TITLE
Adding New Beacon UUID

### ISSUE THREAD

**Issue by mangopudding** [madewithpepper/track-my-gear#1]
### Version
1.0.3

### Steps to reproduce
1.  Launch App
2.  Tap on "Add Beacon"
3.  Fill out form with Beacon UUID (88888888-8888-8888-8888-888888888888)

### Expected behavior
1) User should be able to add ANY Beacon UUID.
2) Adding Beacon ID feature does not appear to save.

### Actual behavior
It seems that the Beacon UUID is currently hard coded for a specific format.

https://github.com/madewithpepper/track-my-gear/blob/master/www/js/controllers.js#L288

**Current / Restrictive Format**

`var uuidPattern = new RegExp(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);`

**Purposed Change To Allow any Beacon UUID Format**

`var uuidPattern = new RegExp(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);`

When I do enter in the Beacon UUID format, when I click Add Beacon, the status icon spins forever.

I am running the app via Ionic View - do I need to compile to native and run it natively on my iOS or Android device to make this fully functional?

**Comment by skokhuis** [comment]
Thanks, it seems the RegEx doesn't allow that UUID while it's valid. But this project isn't supported anymore, it still uses Ionic 1.

In order to work with beacons you need to run on a device that supports Bluetooth.

**Comment by mangopudding** [comment]
Hi!  I got an Ionic 1 environment running still and I figured out what was wrong.  :)

So, you can't use Ionic View to view the app.  You can deploy it to iOS Simulator or real iOS device - then it will work.  :)
